replicaCount: 2

image:
  repository: 382170164329.dkr.ecr.ap-south-1.amazonaws.com/habitapp
  tag: "ab5a554"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 80
  targetPort: 8080

containerPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  readiness:
    path: /api/habits
    initialDelaySeconds: 20
    periodSeconds: 10

  liveness:
    path: /api/habits
    initialDelaySeconds: 40
    periodSeconds: 20
