apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitapp
  namespace: habitapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: habitapp
  template:
    metadata:
      labels:
        app: habitapp
    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: habitapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
